artifact_uri: file:///C:/Users/Foram/Projects/Fintech Recommender System/fintech-recommender/mlflow/291677211826088830/b0529c80b8c04eff879a909d55addb16/artifacts
end_time: 1774189360259
entry_point_name: ''
experiment_id: '291677211826088830'
lifecycle_stage: active
run_id: b0529c80b8c04eff879a909d55addb16
run_name: delicate-ant-584
source_name: ''
source_type: 4
source_version: ''
start_time: 1774189360195
status: 3
tags: []
user_id: Foram
