artifact_location: file:///C:/Users/Foram/Projects/Fintech Recommender System/fintech-recommender/mlflow/291677211826088830
creation_time: 1774189183439
experiment_id: '291677211826088830'
last_update_time: 1774189183439
lifecycle_stage: active
name: fintech_recommender_als
workspace: default
